### ISSUE TITLE
nested comments

### ISSUE THREAD

**Issue by AurelDragut** [actuallymab/laravel-comment#10]
Hey, i have made comments also commentable to get nested comments.

i made comments commentable and i got them nested  but i don't quite see a proper way to count the children of the comments on the number of the main model's comments...

i would do a 
``` 
foreach ($model->comments as $comment) {
         $totalcomments += $comment->comments->count(); 
}
```
but i get an error about some trait, i guess there is a conflict between commentable and cancomment

**Comment by AurelDragut** [comment]
Any news on this issue, mate?

**Comment by ShortlyMAB** [comment]
Hi @AurelDragut. First, thank you for your support & ping on this. I was unable to think this package as you mentioned, I will upgrade this package's version to 1.0.0 in a few days with this update.

**Comment by AurelDragut** [comment]
Maybe i didnt explain well enough. Anyway this can get alot better and as soon as i get how to do it i will be happy to help on it. I am also thinking about a notification system: any user that comments on a model object can get notified of any new comment that is added to that model object (either that is a model object or a comment added to that model object).

**Comment by ShortlyMAB** [comment]
Hi @AurelDragut could you please check out this example? https://github.com/actuallymab/laravel-comment/blob/master/tests/CommentTest.php#L147 

Also, you can find a basic nested Comment object at https://github.com/actuallymab/laravel-comment/blob/master/tests/Models/Comment.php

**Comment by AurelDragut** [comment]
Sorry, mate, i have no experience with tests. i don't know how to do tests yet.

**Comment by ShortlyMAB** [comment]
You might seem that as an example.

**Comment by ShortlyMAB** [comment]
If anything wrong or misunderstand, you can reopen issue.
