### ISSUE TITLE
how to get comments?

### ISSUE THREAD

**Issue by visherandro** [actuallymab/laravel-comment#15]
How do i get comments of a model

**Comment by visherandro** [comment]
Mybad.  
$blog->comments()->paginate(20)
gives me comments for that blog

**Comment by a-ssassi-n** [comment]
@visherandro  Are you able to get the User info with the comment id?
`$comments = $post->comments()->paginate(10);` 
This gives me the comments which I am able to show like this: 
```
@foreach($comments as $comment)
    Id: {{ $comment->id }} Comment: {{ $comment->comment }}
@endforech
```
But how to get the user attributes like user id, email, username etc with this?
