### ISSUE TITLE
How to use my own CommentModel?

### ISSUE THREAD

**Issue by mathisloge** [actuallymab/laravel-comment#16]
I have an own CommentModel in App\Models\Comment. 

How should I tell the package to use my Model instead of yours? 

Right now im overriding the Traits. Buts thats ... you know

**Comment by ShortlyMAB** [comment]
You can see the answer on readme under

> If you want to have your own Comment Model create a new one and extend my Comment model.

**Comment by mathisloge** [comment]
I´ve extended your Model 
```
<?php


namespace App\Models;


use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;

class Comment extends \Actuallymab\LaravelComment\Models\Comment implements HasMediaConversions
{
    use HasMediaTrait;

    .... functions here ....
}
````

But the Traits still uses yours. I think it should be in a config file, wich Model it should use.
