### ISSUE TITLE
How to get the user's attributes with the comment?

### ISSUE THREAD

**Issue by a-ssassi-n** [actuallymab/laravel-comment#17]
`$comments = $post->comments()->paginate(10);`
This gives me the comments which I am able to show like this:

```
@foreach($comments as $comment)
    Id: {{ $comment->id }} Comment: {{ $comment->comment }}
@endforech
```
But how to get the user attributes like user id, email, username etc with this?

**Comment by zAbdelAziz** [comment]
I think that would go as `$comment->commented`
to explain it further, you can declare a variable in your view as follows and use it.

```
@foreach ($comments as $comment)
<!-- {{ $comment_user = $comment->commented }}-->
@endforeach
```

hope it works for you
