### ISSUE TITLE
Its possible to "Reply" a Comment ?

### ISSUE THREAD

**Issue by brunonetadmin** [actuallymab/laravel-comment#22]
Hi, Its possible to Reply a comment with this package ? If already possible, can you update your docs with this functions? And if not, its possible to add ?

Thanks.

**Comment by a-ssassi-n** [comment]
You may try this:

`$reply->makeChildOf($request->parentid); //parentid is the id of the parent comment
`

**Comment by ykh** [comment]
@a-ssassi-n 
There is no any field to mention parent-id in db-migration file!
How it works? (really it works?!)

**Comment by webineh** [comment]
please add replay method

**Comment by whycomeing** [comment]
> 请添加重播方法
How to add？
