### ISSUE TITLE
Migrations file

### ISSUE THREAD

**Issue by Livijn** [actuallymab/laravel-comment#23]
Hi, just wondering if there is any reason why you are not using the migration file like this:

Old:
   ```
$table->string('commentable_id')->nullable();
$table->string('commentable_type')->nullable();
$table->index(['commentable_id', 'commentable_type']);
$table->string('commented_id')->nullable();
$table->string('commented_type')->nullable();
$table->index(['commented_id', 'commented_type']);
```

New:
  ```
$table->morphs('commentable')->nullable();
$table->morphs('commented')->nullable();
```

Also, I think the names of the rows maybe should be *sender* and *receiver* instead?

**Comment by aalaap** [comment]
5.2 onwards, Laravel contains a `nullableMorphs` method which can make this even cleaner:

    $table->nullableMorphs('commentable');
    $table->nullableMorphs('commented');

@Livijn I don't see why this should be a problem. Why don't you go ahead and submit a PR?
