### ISSUE TITLE
when i install va Composer

### ISSUE THREAD

**Issue by tareqdokhan** [actuallymab/laravel-comment#28]
$ composer require actuallymab/laravel-comment
Using version ^0.5.0 for actuallymab/laravel-comment
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for actuallymab/laravel-comment ^0.5.0 -> satisfiable by actuallymab/laravel-comment[0.5.0].
    - Conclusion: remove laravel/framework v5.5.34
    - Conclusion: don't install laravel/framework v5.5.34
    - actuallymab/laravel-comment 0.5.0 requires illuminate/database 5.6.* -> satisfiable by illuminate/database[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/database v5.6.0|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.1|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.10|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.11|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.12|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.13|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.14|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.15|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.16|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.17|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.2|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.3|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.4|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.5|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.6|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.7|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.8|don't install laravel/framework v5.5.34
    - don't install illuminate/database v5.6.9|don't install laravel/framework v5.5.34
    - Installation request for laravel/framework (locked at v5.5.34, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.34].

Installation failed, reverting ./composer.json to its original content.

**Comment by webineh** [comment]
use version ^0.4.0
