### ISSUE TITLE
Using own comments model not working

### ISSUE THREAD

**Issue by ghost** [actuallymab/laravel-comment#32]
I'm trying to use my own Comment model (so that I can include trashed/soft deleted users in the commented() relationship).  

I've got a model that extends Actuallymab\LaravelComment\Comment as per the readme, but it seems to still be referring to the vendor model rather than my own.  I've also tried extending Actuallymab\LaravelComment\Models\Comment with the same result.

It looks like there's some info missing from the readme on how to do this, or it isn't functioning correctly.  Are you able to assist?

I believe this is the same issue the person in #16 was having, but that was closed without any solution to their issue.

**Comment by aalaap** [comment]
@CJau The traits have the package's model reference hard-coded in the `comments()` method, so you will have to override that. Create and use your own `Commentable` trait with the following code:

    <?php

    namespace App\Models\Traits;

    use App\Models\Comment;

    trait Commentable
    {
        use \Actuallymab\LaravelComment\Commentable;

        /**
         * @return \Illuminate\Database\Eloquent\Relations\MorphMany
         */
        public function comments()
        {
            return $this->morphMany(Comment::class, 'commentable');
        }
    }

This uses the original trait, so you only have to use this trait and not both in your models.
