### ISSUE TITLE
User CanComment and HasComments

### ISSUE THREAD

**Issue by karpovigorok** [actuallymab/laravel-comment#52]
Hi,

Do you have any idea, how to implement when User can comment another User?

I'm trying to do something like this:

`use Actuallymab\LaravelComment\CanComment;
use Actuallymab\LaravelComment\HasComments;

class User extends Authenticatable implements Commentable
{
    use Notifiable, CanFavorite, CanBeFavorited;
    use CanComment, HasComments;
}`
 and getting error:
Symfony\Component\Debug\Exception\FatalErrorException
Trait method comments has not been applied, because there are collisions with other trait methods on App\User

Laravel 6, php 7.3

**Comment by ShortlyMAB** [comment]
Hi @karpovigorok 

You can resolve this with `insteadof` operator: https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict

**Comment by elephantux** [comment]
> You can resolve this with `insteadof` operator: https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict

Can you please show an code example?
