### ISSUE TITLE
Call to undefined method Illuminate\\Database\\Query\\Builder::comment()

### ISSUE THREAD

**Issue by physio** [actuallymab/laravel-comment#6]
I have laravel 5.3, I follow the documentation, but when insert
`$user->comment($product, 'Lorem ipsum ..', 3);` 

the system answer:
`  "message": "Call to undefined method Illuminate\\Database\\Query\\Builder::comment()",
  "status_code": 500,
  "debug": {
    "line": 2450,
    "file": "/opt/lampp/htdocs/test/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
    "class": "BadMethodCallException",
`

**Comment by ShortlyMAB** [comment]
Did you include `CanComment` trait in your `User` model?

**Comment by physio** [comment]
<?php

namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Notifications\Notifiable;
....
....
use Actuallymab\LaravelComment\CanComment;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable, EntrustUserTrait, Friendable;

**Comment by physio** [comment]
sorry i forget to insert CanComment into User model. 

thank you
