### ISSUE TITLE
Question re:version "0.1.1"

### ISSUE THREAD

**Issue by jschlies** [actuallymab/laravel-comment#8]
For reasons I'm unable to get into in this venue, I am unable to upgrade to PHP 7 or Lavarel 5.3 for the mext several months. I have some questions re:version "0.1.1":

- Is version "0.1.1" in a 'releasable' form
- If/When version "0.1.1" was the current release, was any documentation/examples/instructions available? If yes, may I get a copy.

**Comment by ShortlyMAB** [comment]
Hi,

0.2.* is compatible with 5.3. For older versions please use 0.1.1 version. You can find documentation at readme.md file.
