### ISSUE TITLE
commented_id is null

### ISSUE THREAD

**Issue by glore** [actuallymab/laravel-comment#9]
my User primateKey is uid, so all my comment's commented_id is null! help!

**Comment by ShortlyMAB** [comment]
Could you please try to modify `CreateCommentsTable` migration class that created with `php artisan vendor:publish` command.

**Comment by glore** [comment]
how to change , i think should change code:
` 'commented_id'   => $this->id,`  =>
` 'commented_id'   => $this->id(),`
